services:  
  copart-parser:
    container_name: simple-server-status
    restart: unless-stopped
    build: .
    ports:
      - "${PORT}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./app:/app